### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by antonv6**
Arrays and languages are 100% translated, strings -- about 90%.

Things to note: quantity strings `sourceInfo` and `indexInfo` should really use [plurals](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals), because they name the counted objects and it means that the correct spelling depends on the actual numbers (probably never was an issue in e.g. English because no dictionary ever had just 1 word).

### CODE REVIEW

**Comment by rdoeffinger** [comment]
I'm hoping to do a release soon, and after merging this one.
Do you think it is fine for release as-is (as soon as I actually get around to it) or would you rather have a few more days to look over it once more and you tell me when it's ready?

**Comment by rdoeffinger** [comment]
I forgot: resConfigs in build.gradle should also be updated to reflect the new translation.
I am not sure if or when that would have a visible effect, but it's definitely the correct thing to do.

**Comment by antonv6** [comment]
It's ready.

(I couldn't find resConfigs in build.gradle though)

**Comment by rdoeffinger** [comment]
Merged, and I updated resConfigs in 18cae136ffa81c0ec3f408716b62aa610a84eb01 (excuse the embarrassing typo in the commit message...)

**Comment by antonv6** [comment]
I got curious about resConfigs, since other projects that I contributed to never mentioned that. Not being an android developer, I found a couple of pages giving examples, in particular this: https://developer.android.com/studio/build/optimize-your-build.html#reduce_resources

So it looks like it only compiles variants that are explicitly specified there. So does it mean that the current resConfigs will only include language-specific resources and will drop `values-v11`, `values-v14` and such and also all extra drawables?

**Comment by rdoeffinger** [comment]
To be honest, I barely know what I am doing...
However I can see from the apk that all the various drawables are still included, so either it just doesn't actually work properly, or maybe it is more clever and removes only *dpi stuff if you specified one dpi value there.
Apart from this basic sanity checking I guess I'm simply hoping for someone to complain if it actually broke something :)

**Pull request merged**
