### PR TITLE
--added: Brazilian Portuguese translation (values-pt-rBR/)

### PR DESCRIPTION
**Pull request by a-ira**
Feel free to merge...

--

'Akira

### CODE REVIEW

**Comment by rdoeffinger** [comment]
Thanks, but the translations should not contain any of the "translatable=false" strings, the point of those is exactly to not need/prevent them appearing in the translations.
Also, if you can easily do it, merging it into one single commit is nicer (but doesn't matter much).

**Comment by rdoeffinger** [comment]
Also if you couldn't/didn't want to translate something please just leave it out so that tools detect it as missing (unless you just missed them).
Examples of what I mean:
<string name="notWritable"> <VOLTA_AQUI> Dictionary location %s not writable, change in settings.</string>
<string name="defaultDicTitle">Default Dic</string>
<string name="defaultDicSummary">The directory to fired up when nothing else mentioned.</string>

**Comment by rdoeffinger** [comment]
Sorry for so many comments.
I think you should also remove the translatable="false" from FreeSerif.
While it will not really be translated in most languages, there is a "translation" of it in the Japanese language file, so I think it would be incorrect to mark it this way.

**Comment by a-ira** [comment]
Hi. Thank you for the tips. I will revise the files and return to you with a new pull request =D


--

'Akira

**Comment by a-ira** [comment]
I think it is done, now ;)

--

'Akira

**Comment by rdoeffinger** [comment]
Thanks, merged.

**Pull request merged**
